import type { Metadata } from 'next';
import './globals.css';
import LayoutWrapper from '../components/LayoutWrapper';


export const metadata: Metadata = {
  title: 'ALFA',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <html lang="en">
        <body dir="rtl" className="px-12 py-4 overflow-x-hidden">
          <LayoutWrapper>{children}</LayoutWrapper>
          <div id="modal-root"></div>
        </body>
      </html>
    </html>
  );
}


