import type { Metadata } from 'next';
import './globals.css';
import Header from '../components/header/header';
import FooterContainer from '../components/footer/container';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body dir="rtl" className="mx-12 my-4 overflow-x-hidden">
        <Header />
        {children}
        <FooterContainer/>
      </body>
    </html>
  );
}
